#!/bin/sh
tmp=/tmp/malice-`date +%s`
tooldir=`dirname $0`
mkdir $tmp

#iterate all alice programs
for ex in ${1%%/}/*.alice; do
  file=`basename $ex`
  echo "$file:"
  echo -n "  Compiling: "
  $tooldir/compile $ex ${ex%%.alice} 2> /dev/null
  echo $? > $tmp/${file%%.alice}.compilation-student

  # if alice program should not compile
  if [ "$(cat ${ex%%.alice}.compilation)" != "0" ]; then
    if [ "$(cat $tmp/${file%%.alice}.compilation-student)" != "0" ]; then
      echo "OK (compilation failure expected)"
    else
      # student compiler missed errors
      echo "FAIL (compilation should not have succeeded)"
    fi
  else
    if [ "$(cat $tmp/${file%%.alice}.compilation-student)" != "0" ]; then
      echo "FAIL (compilation should have succeeded)"
    else
      echo "OK"

      #for each input data set
      for input in ${ex%%.alice}.*.input; do
        inputf=`basename $input`
        echo "** Testing $input:"
        ${ex%%.alice} > $tmp/${inputf%%.input}.output-student < ${input}
        echo $? > $tmp/${inputf%%.input}.retvalue-student

        if cmp --silent ${input%%.input}.retvalue ${tmp}/${inputf%%.input}.retvalue-student && cmp --silent ${ex%%.alice} > ${input%%.input}.output ${ex%%.alice} > ${tmp}/${inputf%%.input}.output-student; then
          echo all good
        else
          echo failed
        fi
      done
    fi
  fi
  echo
done

rm -Rf $tmp
